// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAmK51c9B1SCBXMCU2Sv8gYwDe8RzHTHk',
    appId: '1:1096854380767:web:63816dc1372647b8d8c96a',
    messagingSenderId: '1096854380767',
    projectId: 'adopet-45bf0',
    authDomain: 'adopet-45bf0.firebaseapp.com',
    storageBucket: 'adopet-45bf0.firebasestorage.app',
    measurementId: 'G-F2SKP73ZJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ngpS_91sdlWrqFCvb9GOIvmg3lUaPyQ',
    appId: '1:1096854380767:android:c9812365ed23091cd8c96a',
    messagingSenderId: '1096854380767',
    projectId: 'adopet-45bf0',
    storageBucket: 'adopet-45bf0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAmK51c9B1SCBXMCU2Sv8gYwDe8RzHTHk',
    appId: '1:1096854380767:web:433bd7947703bc3cd8c96a',
    messagingSenderId: '1096854380767',
    projectId: 'adopet-45bf0',
    authDomain: 'adopet-45bf0.firebaseapp.com',
    storageBucket: 'adopet-45bf0.firebasestorage.app',
    measurementId: 'G-NEE515912X',
  );

}